# MLflow配置文件
# mlflow server configuration
default_artifact_root: ./mlflow/artifacts
# 指定MLflow存储artifacts的默认路径。
host: 127.0.0.1
port: 5000
# 指定MLflow server的主机地址和端口号

# experiment configuration
experiment_name: LSTM for Stock Prediction
# 指定实验名称

# run configuration
run_name: lstm_run
# 指定本次运行的名称

artifact_location: ./mlflow_output
entry_point: train.py

params:
  seq_len: 10
  feature_num: 10
  hidden_dim: 2
  num_layers: 2
  output_dim: 1
  batch_size: 5
  learning_rate: 0.1
  num_epochs: 50

conda_env: ./conda.yaml


model_path: ./mlflow/models
model_name: lstm_model
model_signature: predict
model_description: LSTM model for stock prediction


test_set_size: 0.1


logging_level: info
log_metrics: [loss]
log_params: [batch_size, num_epochs, learning_rate, hidden_dim, num_layers, test_set_size]


tags:
    source: LSTM for stock prediction
    author: Your Name

